spring:
  datasource:
    url: jdbc:h2:tcp://127.0.0.1/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        spring:
  devtools:
    restart:
      enabled: false
  profiles:
    active: local
logging.level:
  org.hibernate.SQL: debug
#  thymelef:
#    prefix: classpath:templates/
#    suffix: .html

